### ISSUE TITLE
Repositioning options

### ISSUE THREAD

**Issue by Madis0** [Dinolek/DiUI#1]
The HUD elements look pretty cool, but I don't really like the positions. Have you considered making them configurable?

**Comment by Dinolek** [comment]
I can look in to it. Should it be more like x, y coordinates or left top, bottom left etc?

**Comment by Madis0** [comment]
I think the alignment (left top, bottom left etc) would be good with a padding setting for extra precision.

**Comment by Dinolek** [comment]
Added in 127fba2adcf8e68ed7abf65e61056b936f71d210

**Comment by Dinolek** [comment]
Added in 127fba2adcf8e68ed7abf65e61056b936f71d210
