### ISSUE TITLE
Graphical glitch with XP count

### ISSUE THREAD

**Issue by Madis0** [Dinolek/DiUI#3]
- Minecraft 1.14.1
- DiUI 1.0.1
- Fabric API 0.3.0 pb 165
- Fabric Loader 0.4.7 b 147

.

- Hotbar: bottom middle
- Status bars: bottom left (seems to happen only with that position)
- Padding: 3
- Swap HP with EXP: yes

![2019-05-21_16 05 20](https://user-images.githubusercontent.com/8611110/58098546-79ee5a80-7be2-11e9-977a-0995d5a13827.png)

**Comment by Dinolek** [comment]
Thanks, I accidentally mixed scaled height with width, will post fixed version later

**Comment by Dinolek** [comment]
Fixed in efa6c2863def9125e481f22d95728d7f15013a41
