### ISSUE TITLE
Config screen won't open in 1.0.4

### ISSUE THREAD

**Issue by Madis0** [Dinolek/DiUI#5]
In DiUI 1.0.4 it is not possible to configure the mod, as clicking the cog button in ModMenu does nothing.

- Minecraft 1.14.4
- DiUI 1.0.4
- ModMenu 1.7.8 b 117
- Fabric API 0.3.1 b 208

**Comment by Dinolek** [comment]
You need cloth config for this.

**Comment by Madis0** [comment]
[Cloth Config's Curseforge claims](https://www.curseforge.com/minecraft/mc-mods/cloth-config) that the mod developer should embed it, instead of being a separate download. Either way, this still does not work when adding Cloth Config 2 1.1.1 to the mods folder.

**Comment by Dinolek** [comment]
I didn't want to do that, but will do to not confuse people.
https://www.curseforge.com/minecraft/mc-mods/diui/files/2771189
